---
services:
  ansible:
    build:
      context: ansible/
      dockerfile: Dockerfile
      args:
        - UID
        - GID
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ../:/workspace
  terraform:
    build:
      context: terraform/
      dockerfile: Dockerfile
      args:
        - UID
        - GID
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ../:/workspace
