---
- name: Check if swap is enabled
  ansible.builtin.command: swapon --noheadings --show
  register: swap_status
  changed_when: false

- name: Disable swap if active
  ansible.builtin.command: swapoff -a
  when: swap_status.stdout != ""
  changed_when: true

- name: Ensure swap is disabled in /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^\s*(?!#).*[\s\t]+swap[\s\t]'
    backup: true
    state: absent
