---
- name: Add docker repository
  ansible.builtin.command:
    cmd: dnf config-manager --add-repo {{ docker_repo_url }}
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install docker packages
  ansible.builtin.dnf:
    name: "{{ package }}"
  with_items: "{{ docker_packages }}"
  loop_control:
    loop_var: package
  notify: Restart docker service
  when: not ansible_check_mode

- name: Enable and Start docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  when: not ansible_check_mode
