[project]
name = "ansible-workspace"
version = "0.1.0"
description = "Development and execution environment for Ansible"
readme = "README.md"
requires-python = "==3.13.3"
dependencies = ["ansible==11.5.0", "argcomplete==3.6.2", "passlib==1.7.4"]

[dependency-groups]
dev = ["ansible-lint==25.4.0"]
